/* (C)2026 */
package com.github.lamarios.podku.staticContent;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class StaticContentController {
  /**
   * Serves the main index HTML file.
   *
   * <p>javadoc generated by AI
   */
  @RequestMapping(value = "/")
  public String serveIndex() {
    return "index.html";
  }
}
