/* (C)2026 */
package com.github.lamarios.podku.models;

public interface Person {
  /**
   * Retrieves the person name.
   *
   * @return the name
   *     <p>javadoc generated by AI
   */
  String getName();

  /**
   * Sets the person name.
   *
   * @param name the name to set
   *     <p>javadoc generated by AI
   */
  void setName(String name);

  /**
   * Retrieves the role of the person.
   *
   * @return the role
   *     <p>javadoc generated by AI
   */
  String getRole();

  /**
   * Sets the role of the person.
   *
   * @param role the role to set
   *     <p>javadoc generated by AI
   */
  void setRole(String role);

  /**
   * Retrieves the group the person belongs to.
   *
   * @return the group
   *     <p>javadoc generated by AI
   */
  String getGroup();

  /**
   * Sets the group the person belongs to.
   *
   * @param group the group to set
   *     <p>javadoc generated by AI
   */
  void setGroup(String group);

  /**
   * Retrieves the image URL or path of the person.
   *
   * @return the image URL or path
   *     <p>javadoc generated by AI
   */
  String getImage();

  /**
   * Sets the image URL or path of the person.
   *
   * @param image the image URL or path to set
   *     <p>javadoc generated by AI
   */
  void setImage(String image);

  /**
   * Retrieves the link associated with the person.
   *
   * @return the link URL
   *     <p>javadoc generated by AI
   */
  String getLink();

  /**
   * Sets the link associated with the person.
   *
   * @param link the link URL to set
   *     <p>javadoc generated by AI
   */
  void setLink(String link);
}
