/* (C)2026 */
package com.github.lamarios.podku.transcripts;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.github.lamarios.podku.episodes.Episode;
import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "episode_transcripts")
public class EpisodeTranscript {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  @ManyToOne
  @JoinColumn(name = "episode_id")
  @JsonIgnore
  private Episode episode;

  private String startTime;
  private String endTime;
  private String speaker;
  private String content;
  private String language;

  @Transient private String highlightedContent;

  /**
   * Returns highlighted search result snippet content.
   *
   * @return highlighted text
   *     <p>javadoc generated by AI
   */
  public String getHighlightedContent() {
    return highlightedContent;
  }

  /**
   * Sets highlighted snippet content.
   *
   * @param highlightedContent highlighted text
   *     <p>javadoc generated by AI
   */
  public void setHighlightedContent(String highlightedContent) {
    this.highlightedContent = highlightedContent;
  }

  /**
   * Returns the transcript identifier.
   *
   * @return UUID of the transcript
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the transcript identifier.
   *
   * @param id UUID of the transcript
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Returns the associated episode.
   *
   * @return episode entity
   *     <p>javadoc generated by AI
   */
  public Episode getEpisode() {
    return episode;
  }

  /**
   * Sets the associated episode.
   *
   * @param episode episode entity
   *     <p>javadoc generated by AI
   */
  public void setEpisode(Episode episode) {
    this.episode = episode;
  }

  /**
   * Returns the start timestamp string.
   *
   * @return start timestamp
   *     <p>javadoc generated by AI
   */
  public String getStartTime() {
    return startTime;
  }

  /**
   * Sets the start timestamp string.
   *
   * @param startTime start timestamp
   *     <p>javadoc generated by AI
   */
  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  /**
   * Returns the end timestamp string.
   *
   * @return end timestamp
   *     <p>javadoc generated by AI
   */
  public String getEndTime() {
    return endTime;
  }

  /**
   * Sets the end timestamp string.
   *
   * @param endTime end timestamp
   *     <p>javadoc generated by AI
   */
  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  /**
   * Returns the speaker name if identified.
   *
   * @return speaker name
   *     <p>javadoc generated by AI
   */
  public String getSpeaker() {
    return speaker;
  }

  /**
   * Sets the speaker name.
   *
   * @param speaker speaker name
   *     <p>javadoc generated by AI
   */
  public void setSpeaker(String speaker) {
    this.speaker = speaker;
  }

  /**
   * Returns the spoken text content.
   *
   * @return spoken transcript text
   *     <p>javadoc generated by AI
   */
  public String getContent() {
    return content;
  }

  /**
   * Sets the spoken text content.
   *
   * @param content spoken transcript text
   *     <p>javadoc generated by AI
   */
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * Returns the language of the utterance.
   *
   * @return the language code
   *     <p>javadoc generated by AI
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the language of the utterance.
   *
   * @param language the language code
   *     <p>javadoc generated by AI
   */
  public void setLanguage(String language) {
    this.language = language;
  }
}
