/* (C)2026 */
package com.github.lamarios.podku.transcripts;

import com.github.lamarios.podku.episodes.Episode;
import jakarta.persistence.Tuple;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface EpisodeTranscriptRepository extends JpaRepository<EpisodeTranscript, UUID> {
  /**
   * Finds the first transcript line for an episode in a specific language.
   *
   * @param episode the episode entity
   * @param language the language code
   * @return matching transcript object or null
   *     <p>javadoc generated by AI
   */
  Object findFirstByEpisodeEqualsAndLanguage(Episode episode, String language);

  /**
   * Retrieves all distinct language codes available for an episode's transcripts.
   *
   * @param episode the episode entity
   * @return list of distinct language codes
   *     <p>javadoc generated by AI
   */
  @Query("select distinct t.language from EpisodeTranscript t where t.episode = :episode")
  List<String> findDistinctLanguagesForEpisode(Episode episode);

  /**
   * Retrieves all transcripts for an episode with sorting.
   *
   * @param episode the episode entity
   * @param sort sorting options
   * @return sorted list of transcripts
   *     <p>javadoc generated by AI
   */
  List<EpisodeTranscript> findAllByEpisode(Episode episode, Sort sort);

  /**
   * Retrieves all transcripts for an episode in a specific language with sorting.
   *
   * @param episode the episode entity
   * @param language the language code
   * @param sort sorting options
   * @return sorted list of transcripts
   *     <p>javadoc generated by AI
   */
  List<EpisodeTranscript> findAllByEpisodeAndLanguage(Episode episode, String language, Sort sort);

  /**
   * Performs full-text search across transcripts for given episodes.
   *
   * @param query the search query
   * @param episodeIds array of episode UUIDs
   * @return list of matching tuples with highlighted content
   *     <p>javadoc generated by AI
   */
  @Query(
      value =
          """
            SELECT et.*,
            TS_HEADLINE(
                'english',
                et.content,
                TO_TSQUERY('english', :query),
                'StartSel=§, StopSel=§, HighlightAll=true'
            ) AS highlighted_content
            FROM  episode_transcripts et
            WHERE  et.search_vector @@ TO_TSQUERY('english', :query)
            AND et.episode_id = ANY(:episodes)
            """,
      nativeQuery = true)
  List<Tuple> search(@Param("query") String query, @Param("episodes") UUID[] episodeIds);

  /**
   * Finds all transcripts belonging to the specified collection of episodes.
   *
   * @param episodes collection of episode entities
   * @return list of transcripts
   *     <p>javadoc generated by AI
   */
  List<EpisodeTranscript> findAllByEpisodeIn(Collection<Episode> episodes);

  /**
   * Finds transcript lines that overlap a specific timestamp point.
   *
   * @param startTimeBefore timestamp upper bound for segment start
   * @param endTimeAfter timestamp lower bound for segment end
   * @param episode episode entity
   * @return list of covering transcript lines
   *     <p>javadoc generated by AI
   */
  List<EpisodeTranscript> findByStartTimeBeforeAndEndTimeAfterAndEpisode(
      String startTimeBefore, String endTimeAfter, Episode episode);

  /**
   * Finds transcripts within a specific time window for an episode and language.
   *
   * @param episode episode entity
   * @param language language code
   * @param startTimeIsGreaterThan lower start time bound
   * @param endTimeIsLessThan upper end time bound
   * @return list of transcripts in the window
   *     <p>javadoc generated by AI
   */
  List<EpisodeTranscript> findAllByEpisodeAndLanguageAndStartTimeGreaterThanAndEndTimeLessThanEqual(
      Episode episode, String language, String startTimeIsGreaterThan, String endTimeIsLessThan);
}
