/* (C)2026 */
package com.github.lamarios.podku.transcripts;

import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/transcripts")
@Tag(name = "Transcripts")
public class TranscriptController {
  private final TranscriptService transcriptService;

  /**
   * Creates the controller with its dependencies.
   *
   * @param transcriptService service used to fetch transcripts javadoc generated by AI
   */
  @Autowired
  public TranscriptController(TranscriptService transcriptService) {
    this.transcriptService = transcriptService;
  }

  /**
   * Returns the transcript languages available for an episode.
   *
   * @param id the episode identifier
   * @return list of language codes javadoc generated by AI
   */
  @GetMapping("{id}/languages")
  public List<String> getEpisodeLanguages(@PathVariable String id) {
    return transcriptService.getLanguages(id);
  }

  /**
   * Returns the transcript lines for an episode in a given language.
   *
   * @param id the episode identifier
   * @param language the transcript language to fetch
   * @return list of transcript lines javadoc generated by AI
   */
  @GetMapping("{id}/{language}")
  public List<EpisodeTranscript> getTranscript(
      @PathVariable String id, @PathVariable String language) {
    return transcriptService.getTranscript(id, language);
  }
}
