/* (C)2026 */
package com.github.lamarios.podku.transcripts;

import com.github.lamarios.podku.episodes.EpisodeService;
import java.util.Collections;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TranscriptService {
  private final EpisodeService episodeService;
  private final EpisodeTranscriptRepository episodeTranscriptRepository;

  /**
   * Constructs the TranscriptService with required repositories and services.
   *
   * @param episodeService service for episode retrieval
   * @param episodeTranscriptRepository repository for transcript persistence
   *     <p>javadoc generated by AI
   */
  @Autowired
  public TranscriptService(
      EpisodeService episodeService, EpisodeTranscriptRepository episodeTranscriptRepository) {
    this.episodeService = episodeService;
    this.episodeTranscriptRepository = episodeTranscriptRepository;
  }

  /**
   * Retrieves all distinct transcript languages available for an episode.
   *
   * @param id episode identifier
   * @return list of language codes
   *     <p>javadoc generated by AI
   */
  @Transactional(readOnly = true)
  public List<String> getLanguages(String id) {
    var episode = episodeService.getEpisode(id);
    if (episode == null) {
      return Collections.emptyList();
    } else {
      return episodeTranscriptRepository.findDistinctLanguagesForEpisode(episode);
    }
  }

  /**
   * Retrieves all transcript segments for an episode in the specified language, sorted by start
   * time.
   *
   * @param id episode identifier
   * @param language language code
   * @return list of transcript segments
   *     <p>javadoc generated by AI
   */
  @Transactional(readOnly = true)
  public List<EpisodeTranscript> getTranscript(String id, String language) {
    var episode = episodeService.getEpisode(id);
    if (episode == null) {
      return Collections.emptyList();
    } else {
      return episodeTranscriptRepository.findAllByEpisodeAndLanguage(
          episode, language, Sort.by(Sort.Direction.ASC, "startTime"));
    }
  }
}
