package com.github.lamarios.podku.bookmarks;

import com.github.lamarios.podku.episodes.Episode;
import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "episode_bookmarks")
public class Bookmark {

  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private Long time;

  private String topic;

  @ManyToOne
  @JoinColumn(name = "episode_id")
  private Episode episode;

  /**
   * Gets the bookmark identifier.
   *
   * @return UUID of the bookmark
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the bookmark identifier.
   *
   * @param id UUID of the bookmark
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the timestamp of the bookmark in seconds.
   *
   * @return timestamp in seconds
   *     <p>javadoc generated by AI
   */
  public Long getTime() {
    return time;
  }

  /**
   * Gets the AI-generated or user topic for the bookmark.
   *
   * @return topic description
   *     <p>javadoc generated by AI
   */
  public String getTopic() {
    return topic;
  }

  /**
   * Sets the topic for the bookmark.
   *
   * @param topic topic description
   *     <p>javadoc generated by AI
   */
  public void setTopic(String topic) {
    this.topic = topic;
  }

  /**
   * Sets the timestamp of the bookmark in seconds.
   *
   * @param time timestamp in seconds
   *     <p>javadoc generated by AI
   */
  public void setTime(Long time) {
    this.time = time;
  }

  /**
   * Gets the associated episode.
   *
   * @return episode entity
   *     <p>javadoc generated by AI
   */
  public Episode getEpisode() {
    return episode;
  }

  /**
   * Sets the associated episode.
   *
   * @param episode episode entity
   *     <p>javadoc generated by AI
   */
  public void setEpisode(Episode episode) {
    this.episode = episode;
  }
}
