import 'dart:async';
import 'dart:convert';
import 'dart:io';

const _apiPort = 8080;
const _webPort = 8082;

/// This code is fully generated by AI and i don't understand much of it unfortunately
void reverseProxy(Socket client) {
  final buffer = <int>[];
  late StreamSubscription<List<int>> sub;
  Socket? backend;
  var closed = false;

  Future<void> closeAll({bool graceful = false}) async {
    if (closed) return;
    closed = true;
    await sub.cancel();
    if (graceful) {
      try {
        await client.flush();
      } catch (_) {}
      try {
        await client.close();
      } catch (_) {}
    } else {
      try {
        client.destroy();
      } catch (_) {}
    }
    try {
      backend?.destroy();
    } catch (_) {}
  }

  sub = client.listen(
        (chunk) async {
      try {
        if (backend != null) {
          backend!.add(chunk);
          return;
        }
        buffer.addAll(chunk);
        final headerEnd = _findHeaderEnd(buffer);
        if (headerEnd == -1) return;
        final headerText = utf8.decode(buffer.sublist(0, headerEnd));
        final lines = headerText.split('\r\n');
        final requestLine = lines.first;
        final parts = requestLine.split(' ');
        final path = parts.length > 1 ? parts[1] : '/';
        final isApi = path.startsWith('/api');
        final isWs = path.startsWith('/v1/websocket');
        final targetPort = (isApi || isWs) ? _apiPort : _webPort;

        backend = await Socket.connect('localhost', targetPort);

        final strippedPath =
        path == '/api' ? '/' : path.replaceFirst('/api', '');
        var outHeaderText = isApi
            ? headerText.replaceFirst(
          requestLine,
          requestLine.replaceFirst(path, strippedPath),
        )
            : headerText;
        if (!isWs) outHeaderText = _forceConnectionClose(outHeaderText);

        final restAfterHeaders = buffer.sublist(headerEnd);
        backend!.add(utf8.encode(outHeaderText));
        backend!.add(restAfterHeaders);

        backend!.listen(
              (data) {
            try {
              client.add(data);
            } catch (_) {
              closeAll();
            }
          },
          onDone: () => closeAll(graceful: true), // flush before closing
          onError: (_) => closeAll(),
          cancelOnError: true,
        );
      } catch (_) {
        closeAll();
      }
    },
    onDone: () => closeAll(graceful: true),
    onError: (_) => closeAll(),
    cancelOnError: true,
  );
}

String _forceConnectionClose(String headerText) {
  final lines = headerText.split('\r\n');
  final filtered =
  lines.where((l) => !l.toLowerCase().startsWith('connection:')).toList();
  filtered.add('Connection: close');
  return filtered.join('\r\n');
}

int _findHeaderEnd(List<int> bytes) {
  const target = [13, 10, 13, 10]; // \r\n\r\n
  for (var i = 0; i <= bytes.length - target.length; i++) {
    if (bytes[i] == target[0] &&
        bytes[i + 1] == target[1] &&
        bytes[i + 2] == target[2] &&
        bytes[i + 3] == target[3]) {
      return i;
    }
  }
  return -1;
}