import 'dart:async';
import 'dart:convert';
import 'dart:io';

const _apiPort = 8080;
const _webPort = 8082;

/// This code is fully generated by AI and i don't understand much of it unfortunately
void reverseProxy(Socket client) {
  final buffer = <int>[];
  late StreamSubscription<List<int>> sub;
  Socket? backend;
  var closed = false;

  void closeAll() {
    if (closed) return;
    closed = true;
    sub.cancel();
    try {
      client.destroy();
    } catch (_) {}
    try {
      backend?.destroy();
    } catch (_) {}
  }

  sub = client.listen(
    (chunk) async {
      try {
        if (backend != null) {
          backend!.add(chunk);
          return;
        }
        buffer.addAll(chunk);
        final headerEnd = _findHeaderEnd(buffer);
        if (headerEnd == -1) return; // keep buffering (add a size cap in prod)
        final headerText = utf8.decode(buffer.sublist(0, headerEnd));
        final lines = headerText.split('\r\n');
        final requestLine = lines.first;
        final parts = requestLine.split(' '); // METHOD PATH HTTP/1.1
        final path = parts.length > 1 ? parts[1] : '/';
        final isApi = path.startsWith('/api');
        final targetPort = (isApi || path.startsWith('/v1/websocket'))
            ? _apiPort
            : _webPort;

        backend = await Socket.connect('localhost', targetPort);

        // Rewrite the path only when forwarding to the API backend and
        // the /api prefix is present — strip it, same as remainingPath did.
        final strippedPath = path == '/api'
            ? '/'
            : path.replaceFirst('/api', '');
        final outHeaderText = isApi
            ? _forceConnectionClose(
                headerText.replaceFirst(
                  requestLine,
                  requestLine.replaceFirst(path, strippedPath),
                ),
              )
            : path.startsWith('/v1/websocket')
            ? headerText // leave upgrade headers untouched
            : _forceConnectionClose(headerText);

        final restAfterHeaders = buffer.sublist(
          headerEnd,
        ); // includes \r\n\r\n + any body bytes already read
        backend!.add(utf8.encode(outHeaderText));
        backend!.add(restAfterHeaders);
        backend!.listen(
          (data) {
            try {
              client.add(data);
            } catch (_) {
              closeAll();
            }
          },
          onDone: closeAll,
          onError: (_) => closeAll(),
          cancelOnError: true,
        );
      } catch (_) {
        closeAll();
      }
    },
    onDone: closeAll,
    onError: (_) => closeAll(),
    cancelOnError: true,
  );
}

int _findHeaderEnd(List<int> bytes) {
  const target = [13, 10, 13, 10]; // \r\n\r\n
  for (var i = 0; i <= bytes.length - target.length; i++) {
    if (bytes[i] == target[0] &&
        bytes[i + 1] == target[1] &&
        bytes[i + 2] == target[2] &&
        bytes[i + 3] == target[3]) {
      return i;
    }
  }
  return -1;
}

String _forceConnectionClose(String headerText) {
  final lines = headerText.split('\r\n');
  final filtered = lines
      .where((l) => !l.toLowerCase().startsWith('connection:'))
      .toList();
  filtered.add('Connection: close');
  return filtered.join('\r\n');
}
