/* (C)2026 */
package com.github.lamarios.podku.podcasts;

import java.util.List;
import java.util.UUID;

public class PodcastLight {
  private UUID id;
  private String url;
  private String name;
  private String artworkUrl;
  private String description;
  private String author;
  private String link;
  private String color;
  private List<PodcastPerson> people;
  private String artworkEncrypted;

  /**
   * Default constructor.
   *
   * <p>javadoc generated by AI
   */
  public PodcastLight() {}

  /**
   * Constructs a PodcastLight summary from a full Podcast entity.
   *
   * @param podcast the full Podcast entity
   *     <p>javadoc generated by AI
   */
  public PodcastLight(Podcast podcast) {
    id = podcast.getId();
    url = podcast.getUrl();
    name = podcast.getName();
    artworkUrl = podcast.getArtworkUrl();
    description = podcast.getDescription();
    author = podcast.getAuthor();
    link = podcast.getLink();
    people = podcast.getPeople();
    color = podcast.getColor();
    try {
      artworkEncrypted = podcast.getArtworkEncrypted();
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  /**
   * Gets the encrypted artwork URL.
   *
   * @return encrypted URL string
   *     <p>javadoc generated by AI
   */
  public String getArtworkEncrypted() {
    return artworkEncrypted;
  }

  /**
   * Sets the encrypted artwork URL.
   *
   * @param artworkEncrypted encrypted URL string
   *     <p>javadoc generated by AI
   */
  public void setArtworkEncrypted(String artworkEncrypted) {
    this.artworkEncrypted = artworkEncrypted;
  }

  /**
   * Gets the dominant color hex string.
   *
   * @return hex color
   *     <p>javadoc generated by AI
   */
  public String getColor() {
    return color;
  }

  /**
   * Sets the dominant color hex string.
   *
   * @param color hex color
   *     <p>javadoc generated by AI
   */
  public void setColor(String color) {
    this.color = color;
  }

  /**
   * Gets the podcast UUID.
   *
   * @return podcast UUID
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the podcast UUID.
   *
   * @param id podcast UUID
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the podcast RSS feed URL.
   *
   * @return feed URL
   *     <p>javadoc generated by AI
   */
  public String getUrl() {
    return url;
  }

  /**
   * Sets the podcast RSS feed URL.
   *
   * @param url feed URL
   *     <p>javadoc generated by AI
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * Gets the podcast title.
   *
   * @return podcast title
   *     <p>javadoc generated by AI
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the podcast title.
   *
   * @param name podcast title
   *     <p>javadoc generated by AI
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the artwork image URL.
   *
   * @return image URL
   *     <p>javadoc generated by AI
   */
  public String getArtworkUrl() {
    return artworkUrl;
  }

  /**
   * Sets the artwork image URL.
   *
   * @param artworkUrl image URL
   *     <p>javadoc generated by AI
   */
  public void setArtworkUrl(String artworkUrl) {
    this.artworkUrl = artworkUrl;
  }

  /**
   * Gets the podcast description text.
   *
   * @return description
   *     <p>javadoc generated by AI
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the podcast description text.
   *
   * @param description description
   *     <p>javadoc generated by AI
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the podcast author name.
   *
   * @return author name
   *     <p>javadoc generated by AI
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the podcast author name.
   *
   * @param author author name
   *     <p>javadoc generated by AI
   */
  public void setAuthor(String author) {
    this.author = author;
  }

  /**
   * Gets the podcast website link.
   *
   * @return link URL
   *     <p>javadoc generated by AI
   */
  public String getLink() {
    return link;
  }

  /**
   * Sets the podcast website link.
   *
   * @param link link URL
   *     <p>javadoc generated by AI
   */
  public void setLink(String link) {
    this.link = link;
  }

  /**
   * Gets the list of people involved in the podcast.
   *
   * @return list of podcast people
   *     <p>javadoc generated by AI
   */
  public List<PodcastPerson> getPeople() {
    return people;
  }

  /**
   * Sets the list of people involved in the podcast.
   *
   * @param people list of podcast people
   *     <p>javadoc generated by AI
   */
  public void setPeople(List<PodcastPerson> people) {
    this.people = people;
  }
}
