/* (C)2026 */
package com.github.lamarios.podku.podcasts;

import com.github.lamarios.podku.episodes.Episode;
import com.github.lamarios.podku.utils.FastUrlCrypto;
import jakarta.persistence.*;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "podcasts")
public class Podcast {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private String url;
  private String name;
  private String artworkUrl;
  private String description;
  private String author;
  private String link;
  private String color;

  @OneToMany(mappedBy = "podcast", cascade = CascadeType.ALL, orphanRemoval = true)
  @OrderBy("pubDateMillis DESC")
  private List<Episode> episodes;

  @OneToMany(mappedBy = "podcast", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<PodcastPerson> people;

  @Transient private String artworkEncrypted;

  /**
   * Sets the encrypted artwork URL string.
   *
   * @param artworkEncrypted encrypted artwork URL
   *     <p>javadoc generated by AI
   */
  public void setArtworkEncrypted(String artworkEncrypted) {
    this.artworkEncrypted = artworkEncrypted;
  }

  /**
   * Returns or generates the encrypted artwork URL string.
   *
   * @return encrypted artwork URL
   * @throws Exception if encryption fails
   *     <p>javadoc generated by AI
   */
  public String getArtworkEncrypted() throws Exception {
    if (artworkEncrypted != null) {
      return artworkEncrypted;
    } else {
      return FastUrlCrypto.instance.encrypt(artworkUrl);
    }
  }

  /**
   * Gets the podcast UUID.
   *
   * @return podcast identifier
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the podcast UUID.
   *
   * @param id podcast identifier
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the podcast RSS feed URL.
   *
   * @return feed URL
   *     <p>javadoc generated by AI
   */
  public String getUrl() {
    return url;
  }

  /**
   * Sets the podcast RSS feed URL.
   *
   * @param url feed URL
   *     <p>javadoc generated by AI
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * Gets the podcast name.
   *
   * @return podcast name
   *     <p>javadoc generated by AI
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the podcast name.
   *
   * @param name podcast name
   *     <p>javadoc generated by AI
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the artwork image URL.
   *
   * @return image URL
   *     <p>javadoc generated by AI
   */
  public String getArtworkUrl() {
    return artworkUrl;
  }

  /**
   * Sets the artwork image URL.
   *
   * @param artworkUrl image URL
   *     <p>javadoc generated by AI
   */
  public void setArtworkUrl(String artworkUrl) {
    this.artworkUrl = artworkUrl;
  }

  /**
   * Gets the podcast description.
   *
   * @return description
   *     <p>javadoc generated by AI
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the podcast description.
   *
   * @param description description
   *     <p>javadoc generated by AI
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the author of the podcast.
   *
   * @return author name
   *     <p>javadoc generated by AI
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the author of the podcast.
   *
   * @param author author name
   *     <p>javadoc generated by AI
   */
  public void setAuthor(String author) {
    this.author = author;
  }

  /**
   * Gets the website link of the podcast.
   *
   * @return link URL
   *     <p>javadoc generated by AI
   */
  public String getLink() {
    return link;
  }

  /**
   * Sets the website link of the podcast.
   *
   * @param link link URL
   *     <p>javadoc generated by AI
   */
  public void setLink(String link) {
    this.link = link;
  }

  /**
   * Gets the list of episodes for this podcast.
   *
   * @return list of episodes
   *     <p>javadoc generated by AI
   */
  public List<Episode> getEpisodes() {
    return episodes;
  }

  /**
   * Sets the list of episodes for this podcast.
   *
   * @param episodes list of episodes
   *     <p>javadoc generated by AI
   */
  public void setEpisodes(List<Episode> episodes) {
    this.episodes = episodes;
  }

  /**
   * Gets the people associated with this podcast.
   *
   * @return list of podcast people
   *     <p>javadoc generated by AI
   */
  public List<PodcastPerson> getPeople() {
    return people;
  }

  /**
   * Sets the people associated with this podcast.
   *
   * @param people list of podcast people
   *     <p>javadoc generated by AI
   */
  public void setPeople(List<PodcastPerson> people) {
    this.people = people;
  }

  /**
   * Gets the dominant color hex string.
   *
   * @return hex color
   *     <p>javadoc generated by AI
   */
  public String getColor() {
    return color;
  }

  /**
   * Sets the dominant color hex string.
   *
   * @param color hex color
   *     <p>javadoc generated by AI
   */
  public void setColor(String color) {
    this.color = color;
  }
}
