/* (C)2026 */
package com.github.lamarios.podku.podcasts;

/** Checked-style runtime signal that a podcast feed could not be parsed or fetched. */
public class PodcastFeedException extends RuntimeException {
  /**
   * Constructs a new PodcastFeedException with an explanatory message.
   *
   * @param message description of the feed failure
   *     <p>javadoc generated by AI
   */
  public PodcastFeedException(String message) {
    super(message);
  }
}
