/* (C)2026 */
package com.github.lamarios.podku.episodes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "episode_chapters")
public class Chapter {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private Double startTime;
  private String title;
  private String img;
  private Boolean toc = true;
  private Double endTime;

  @ManyToOne
  @JoinColumn(name = "episode_id")
  @JsonIgnore
  private Episode episode;

  /**
   * Gets chapter UUID.
   *
   * @return UUID
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets chapter UUID.
   *
   * @param id UUID
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets chapter start time in seconds.
   *
   * @return start time
   *     <p>javadoc generated by AI
   */
  public Double getStartTime() {
    return startTime;
  }

  /**
   * Sets chapter start time in seconds.
   *
   * @param startTime start time
   *     <p>javadoc generated by AI
   */
  public void setStartTime(Double startTime) {
    this.startTime = startTime;
  }

  /**
   * Gets chapter title.
   *
   * @return chapter title
   *     <p>javadoc generated by AI
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets chapter title.
   *
   * @param title chapter title
   *     <p>javadoc generated by AI
   */
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * Gets chapter artwork image URL.
   *
   * @return image URL
   *     <p>javadoc generated by AI
   */
  public String getImg() {
    return img;
  }

  /**
   * Sets chapter artwork image URL.
   *
   * @param img image URL
   *     <p>javadoc generated by AI
   */
  public void setImg(String img) {
    this.img = img;
  }

  /**
   * Returns whether the chapter should appear in table of contents.
   *
   * @return true if visible in TOC
   *     <p>javadoc generated by AI
   */
  public Boolean getToc() {
    return toc;
  }

  /**
   * Sets whether the chapter should appear in table of contents.
   *
   * @param toc true if visible in TOC
   *     <p>javadoc generated by AI
   */
  public void setToc(Boolean toc) {
    this.toc = toc;
  }

  /**
   * Gets chapter end time in seconds.
   *
   * @return end time
   *     <p>javadoc generated by AI
   */
  public Double getEndTime() {
    return endTime;
  }

  /**
   * Sets chapter end time in seconds.
   *
   * @param endTime end time
   *     <p>javadoc generated by AI
   */
  public void setEndTime(Double endTime) {
    this.endTime = endTime;
  }

  /**
   * Gets the owning episode.
   *
   * @return episode entity
   *     <p>javadoc generated by AI
   */
  public Episode getEpisode() {
    return episode;
  }

  /**
   * Sets the owning episode.
   *
   * @param episode episode entity
   *     <p>javadoc generated by AI
   */
  public void setEpisode(Episode episode) {
    this.episode = episode;
  }
}
