/* (C)2026 */
package com.github.lamarios.podku.episodes;

import java.util.List;

public class Chapters {
  private String version;
  private List<Chapter> chapters;

  /**
   * Gets the chapter metadata version string.
   *
   * @return version string
   *     <p>javadoc generated by AI
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the chapter metadata version string.
   *
   * @param version version string
   *     <p>javadoc generated by AI
   */
  public void setVersion(String version) {
    this.version = version;
  }

  /**
   * Gets the list of parsed chapters.
   *
   * @return list of chapters
   *     <p>javadoc generated by AI
   */
  public List<Chapter> getChapters() {
    return chapters;
  }

  /**
   * Sets the list of parsed chapters.
   *
   * @param chapters list of chapters
   *     <p>javadoc generated by AI
   */
  public void setChapters(List<Chapter> chapters) {
    this.chapters = chapters;
  }
}
