/* (C)2026 */
package com.github.lamarios.podku.episodes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "episode_files")
public class EpisodeFile {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private String url;

  @Enumerated(EnumType.STRING)
  private EpisodeFileType type;

  private String mime;
  private String language;
  private String rel;

  @ManyToOne
  @JoinColumn(name = "episode_id")
  @JsonIgnore
  private Episode episode;

  /**
   * Gets the file UUID.
   *
   * @return UUID
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the file UUID.
   *
   * @param id UUID
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the file URL.
   *
   * @return file URL string
   *     <p>javadoc generated by AI
   */
  public String getUrl() {
    return url;
  }

  /**
   * Sets the file URL.
   *
   * @param url file URL string
   *     <p>javadoc generated by AI
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * Gets the episode file type (transcript, chapters).
   *
   * @return file type
   *     <p>javadoc generated by AI
   */
  public EpisodeFileType getType() {
    return type;
  }

  /**
   * Sets the episode file type.
   *
   * @param type file type
   *     <p>javadoc generated by AI
   */
  public void setType(EpisodeFileType type) {
    this.type = type;
  }

  /**
   * Gets the MIME type of the file.
   *
   * @return MIME type string
   *     <p>javadoc generated by AI
   */
  public String getMime() {
    return mime;
  }

  /**
   * Sets the MIME type of the file.
   *
   * @param mime MIME type string
   *     <p>javadoc generated by AI
   */
  public void setMime(String mime) {
    this.mime = mime;
  }

  /**
   * Gets the language tag for this file.
   *
   * @return language code
   *     <p>javadoc generated by AI
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the language tag for this file.
   *
   * @param language language code
   *     <p>javadoc generated by AI
   */
  public void setLanguage(String language) {
    this.language = language;
  }

  /**
   * Gets the relationship attribute of the file.
   *
   * @return rel string
   *     <p>javadoc generated by AI
   */
  public String getRel() {
    return rel;
  }

  /**
   * Sets the relationship attribute of the file.
   *
   * @param rel rel string
   *     <p>javadoc generated by AI
   */
  public void setRel(String rel) {
    this.rel = rel;
  }

  /**
   * Gets the owning episode.
   *
   * @return episode entity
   *     <p>javadoc generated by AI
   */
  public Episode getEpisode() {
    return episode;
  }

  /**
   * Sets the owning episode.
   *
   * @param episode episode entity
   *     <p>javadoc generated by AI
   */
  public void setEpisode(Episode episode) {
    this.episode = episode;
  }
}
