/* (C)2026 */
package com.github.lamarios.podku.episodes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.lamarios.podku.bookmarks.Bookmark;
import com.github.lamarios.podku.podcasts.Podcast;
import com.github.lamarios.podku.podcasts.PodcastLight;
import com.github.lamarios.podku.transcripts.EpisodeTranscript;
import com.github.lamarios.podku.utils.FastUrlCrypto;
import com.google.common.hash.Hashing;
import jakarta.persistence.*;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "episodes")
public class Episode {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private String title;
  private String description;
  private String audioUrl;
  private String audioType;
  private Long audioLengthBytes;
  private Long pubDateMillis;
  private Long durationSeconds;
  private double progress = 0;
  private String guid;
  private String imageUrl;
  private Integer seasonNumber;
  private Integer episodeNumber;
  private String episodeType;
  private Boolean explicit;
  private String link;
  private boolean processed = false;
  private Long timeUpdated;

  @ManyToOne
  @JoinColumn(name = "podcast_id")
  @JsonIgnore
  private Podcast podcast;

  @Transient private PodcastLight podcastLight;
  @Transient private String audioUrlEncrypted;

  @OneToMany(mappedBy = "episode", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<Chapter> chapters;

  @OneToMany(mappedBy = "episode", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<EpisodeFile> files;

  @OneToMany(mappedBy = "episode", cascade = CascadeType.ALL, orphanRemoval = true)
  @JsonIgnore
  private List<EpisodeTranscript> transcripts;

  @OneToMany(mappedBy = "episode", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<EpisodePerson> people;

  @OneToMany(mappedBy = "episode", cascade = CascadeType.ALL, orphanRemoval = true)
  @JsonIgnore
  private List<Bookmark> bookmarks;

  /**
   * Gets the playback progress in seconds.
   *
   * @return playback position
   *     <p>javadoc generated by AI
   */
  public double getProgress() {
    return progress;
  }

  /**
   * Sets the playback progress in seconds.
   *
   * @param progress playback position
   *     <p>javadoc generated by AI
   */
  public void setProgress(double progress) {
    this.progress = progress;
  }

  /**
   * Checks whether the episode has been processed for transcripts and chapters.
   *
   * @return true if processed
   *     <p>javadoc generated by AI
   */
  public boolean isProcessed() {
    return processed;
  }

  /**
   * JPA callback updating the modification timestamp.
   *
   * <p>javadoc generated by AI
   */
  @PrePersist
  @PreUpdate
  public void onUpdate() {
    timeUpdated = System.currentTimeMillis();
  }

  /**
   * Gets a lightweight summary of the parent podcast.
   *
   * @return PodcastLight summary
   *     <p>javadoc generated by AI
   */
  @Transient
  @JsonProperty("podcast")
  public PodcastLight getPodcastLight() {
    if (podcast != null) {
      return new PodcastLight(podcast);
    } else {
      return podcastLight;
    }
  }

  /**
   * Sets the encrypted audio URL string.
   *
   * @param audioUrlEncrypted encrypted audio URL
   *     <p>javadoc generated by AI
   */
  public void setAudioUrlEncrypted(String audioUrlEncrypted) {
    this.audioUrlEncrypted = audioUrlEncrypted;
  }

  /**
   * Gets or generates the encrypted audio URL string.
   *
   * @return encrypted audio URL
   * @throws Exception if encryption fails
   *     <p>javadoc generated by AI
   */
  public String getAudioUrlEncrypted() throws Exception {
    if (audioUrlEncrypted != null) {
      return audioUrlEncrypted;
    } else {
      return FastUrlCrypto.instance.encrypt(audioUrl);
    }
  }

  /**
   * Sets the lightweight summary of the parent podcast.
   *
   * @param podcastLight podcast summary
   *     <p>javadoc generated by AI
   */
  @Transient
  @JsonProperty("podcast")
  public void setPodcastLight(PodcastLight podcastLight) {
    this.podcastLight = podcastLight;
  }

  /**
   * Sets whether the episode has been processed.
   *
   * @param processed processed flag
   *     <p>javadoc generated by AI
   */
  public void setProcessed(boolean processed) {
    this.processed = processed;
  }

  /**
   * Gets the list of bookmarks for this episode.
   *
   * @return list of bookmarks
   *     <p>javadoc generated by AI
   */
  public List<Bookmark> getBookmarks() {
    return bookmarks;
  }

  /**
   * Sets the list of bookmarks for this episode.
   *
   * @param bookmarks list of bookmarks
   *     <p>javadoc generated by AI
   */
  public void setBookmarks(List<Bookmark> bookmarks) {
    this.bookmarks = bookmarks;
  }

  /**
   * Gets the episode number.
   *
   * @return episode number
   *     <p>javadoc generated by AI
   */
  public Integer getEpisodeNumber() {
    return episodeNumber;
  }

  /**
   * Sets the episode number.
   *
   * @param episodeNumber episode number
   *     <p>javadoc generated by AI
   */
  public void setEpisodeNumber(Integer episodeNumber) {
    this.episodeNumber = episodeNumber;
  }

  /**
   * Gets the episode UUID.
   *
   * @return UUID
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the episode UUID.
   *
   * @param id UUID
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the episode title.
   *
   * @return episode title
   *     <p>javadoc generated by AI
   */
  public String getTitle() {
    return title;
  }

  /**
   * Sets the episode title.
   *
   * @param title episode title
   *     <p>javadoc generated by AI
   */
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * Gets the episode description.
   *
   * @return episode description
   *     <p>javadoc generated by AI
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the episode description.
   *
   * @param description episode description
   *     <p>javadoc generated by AI
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Gets the audio media URL.
   *
   * @return audio URL
   *     <p>javadoc generated by AI
   */
  public String getAudioUrl() {
    return audioUrl;
  }

  /**
   * Sets the audio media URL.
   *
   * @param audioUrl audio URL
   *     <p>javadoc generated by AI
   */
  public void setAudioUrl(String audioUrl) {
    this.audioUrl = audioUrl;
  }

  /**
   * Gets the audio MIME type.
   *
   * @return MIME type
   *     <p>javadoc generated by AI
   */
  public String getAudioType() {
    return audioType;
  }

  /**
   * Sets the audio MIME type.
   *
   * @param audioType MIME type
   *     <p>javadoc generated by AI
   */
  public void setAudioType(String audioType) {
    this.audioType = audioType;
  }

  /**
   * Gets the audio file size in bytes.
   *
   * @return file size in bytes
   *     <p>javadoc generated by AI
   */
  public Long getAudioLengthBytes() {
    return audioLengthBytes;
  }

  /**
   * Sets the audio file size in bytes.
   *
   * @param audioLengthBytes file size in bytes
   *     <p>javadoc generated by AI
   */
  public void setAudioLengthBytes(Long audioLengthBytes) {
    this.audioLengthBytes = audioLengthBytes;
  }

  /**
   * Gets publication date in epoch milliseconds.
   *
   * @return epoch milliseconds
   *     <p>javadoc generated by AI
   */
  public Long getPubDateMillis() {
    return pubDateMillis;
  }

  /**
   * Sets publication date in epoch milliseconds.
   *
   * @param pubDateMillis epoch milliseconds
   *     <p>javadoc generated by AI
   */
  public void setPubDateMillis(Long pubDateMillis) {
    this.pubDateMillis = pubDateMillis;
  }

  /**
   * Gets episode duration in seconds.
   *
   * @return duration in seconds
   *     <p>javadoc generated by AI
   */
  public Long getDurationSeconds() {
    return durationSeconds;
  }

  /**
   * Sets episode duration in seconds.
   *
   * @param durationSeconds duration in seconds
   *     <p>javadoc generated by AI
   */
  public void setDurationSeconds(Long durationSeconds) {
    this.durationSeconds = durationSeconds;
  }

  /**
   * Gets episode unique identifier (GUID).
   *
   * @return GUID
   *     <p>javadoc generated by AI
   */
  public String getGuid() {
    return guid;
  }

  /**
   * Sets episode unique identifier (GUID).
   *
   * @param guid GUID
   *     <p>javadoc generated by AI
   */
  public void setGuid(String guid) {
    this.guid = guid;
  }

  /**
   * Gets episode artwork image URL.
   *
   * @return image URL
   *     <p>javadoc generated by AI
   */
  public String getImageUrl() {
    return imageUrl;
  }

  /**
   * Sets episode artwork image URL.
   *
   * @param imageUrl image URL
   *     <p>javadoc generated by AI
   */
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   * Gets the season number.
   *
   * @return season number
   *     <p>javadoc generated by AI
   */
  public Integer getSeasonNumber() {
    return seasonNumber;
  }

  /**
   * Sets the season number.
   *
   * @param seasonNumber season number
   *     <p>javadoc generated by AI
   */
  public void setSeasonNumber(Integer seasonNumber) {
    this.seasonNumber = seasonNumber;
  }

  /**
   * Gets the episode type (full, trailer, bonus).
   *
   * @return episode type
   *     <p>javadoc generated by AI
   */
  public String getEpisodeType() {
    return episodeType;
  }

  /**
   * Sets the episode type.
   *
   * @param episodeType episode type
   *     <p>javadoc generated by AI
   */
  public void setEpisodeType(String episodeType) {
    this.episodeType = episodeType;
  }

  /**
   * Checks whether the episode contains explicit content.
   *
   * @return true if explicit
   *     <p>javadoc generated by AI
   */
  public Boolean getExplicit() {
    return explicit;
  }

  /**
   * Sets whether the episode contains explicit content.
   *
   * @param explicit explicit flag
   *     <p>javadoc generated by AI
   */
  public void setExplicit(Boolean explicit) {
    this.explicit = explicit;
  }

  /**
   * Gets the webpage link for the episode.
   *
   * @return webpage URL
   *     <p>javadoc generated by AI
   */
  public String getLink() {
    return link;
  }

  /**
   * Sets the webpage link for the episode.
   *
   * @param link webpage URL
   *     <p>javadoc generated by AI
   */
  public void setLink(String link) {
    this.link = link;
  }

  /**
   * Gets the parent podcast.
   *
   * @return podcast entity
   *     <p>javadoc generated by AI
   */
  public Podcast getPodcast() {
    return podcast;
  }

  /**
   * Sets the parent podcast.
   *
   * @param podcast podcast entity
   *     <p>javadoc generated by AI
   */
  public void setPodcast(Podcast podcast) {
    this.podcast = podcast;
  }

  /**
   * Gets the chapters of the episode.
   *
   * @return list of chapters
   *     <p>javadoc generated by AI
   */
  public List<Chapter> getChapters() {
    return chapters;
  }

  /**
   * Sets the chapters of the episode.
   *
   * @param chapters list of chapters
   *     <p>javadoc generated by AI
   */
  public void setChapters(List<Chapter> chapters) {
    this.chapters = chapters;
  }

  /**
   * Gets the supplementary files (transcripts, chapters).
   *
   * @return list of episode files
   *     <p>javadoc generated by AI
   */
  public List<EpisodeFile> getFiles() {
    return files;
  }

  /**
   * Sets the supplementary files.
   *
   * @param files list of episode files
   *     <p>javadoc generated by AI
   */
  public void setFiles(List<EpisodeFile> files) {
    this.files = files;
  }

  /**
   * Gets the transcripts of the episode.
   *
   * @return list of transcripts
   *     <p>javadoc generated by AI
   */
  public List<EpisodeTranscript> getTranscripts() {
    return transcripts;
  }

  /**
   * Sets the transcripts of the episode.
   *
   * @param transcripts list of transcripts
   *     <p>javadoc generated by AI
   */
  public void setTranscripts(List<EpisodeTranscript> transcripts) {
    this.transcripts = transcripts;
  }

  /**
   * Gets people associated with the episode.
   *
   * @return list of people
   *     <p>javadoc generated by AI
   */
  public List<EpisodePerson> getPeople() {
    return people;
  }

  /**
   * Sets people associated with the episode.
   *
   * @param people list of people
   *     <p>javadoc generated by AI
   */
  public void setPeople(List<EpisodePerson> people) {
    this.people = people;
  }

  /**
   * Computes a SHA-256 hash of the audio URL for file caching.
   *
   * @return SHA-256 hash hex string
   *     <p>javadoc generated by AI
   */
  @Transient
  @JsonIgnore
  public String getAudioUrlHash() {
    return Hashing.sha256().hashString(getAudioUrl(), StandardCharsets.UTF_8).toString();
  }

  /**
   * Gets the epoch timestamp when the episode record was last updated.
   *
   * @return update timestamp
   *     <p>javadoc generated by AI
   */
  public Long getTimeUpdated() {
    return timeUpdated;
  }

  /**
   * Sets the epoch timestamp when the episode record was last updated.
   *
   * @param timeUpdated update timestamp
   *     <p>javadoc generated by AI
   */
  public void setTimeUpdated(Long timeUpdated) {
    this.timeUpdated = timeUpdated;
  }
}
