/* (C)2026 */
package com.github.lamarios.podku.episodes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.github.lamarios.podku.models.Person;
import com.github.lamarios.podku.utils.FastUrlCrypto;
import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "episode_people")
public class EpisodePerson implements Person {
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  private String name;
  private String role;

  @Column(name = "`group`")
  private String group;

  private String image;
  private String link;

  @ManyToOne
  @JoinColumn(name = "episode_id")
  @JsonIgnore
  private Episode episode;

  @Transient private String imageEncrypted;

  /**
   * Retrieves the encrypted image URL.
   *
   * @return encrypted image URL
   * @throws Exception if encryption fails
   *     <p>javadoc generated by AI
   */
  public String getImageEncrypted() throws Exception {
    if (imageEncrypted != null) {
      return imageEncrypted;
    } else {
      return FastUrlCrypto.instance.encrypt(image);
    }
  }

  /**
   * Sets the encrypted image URL.
   *
   * @param imageEncrypted encrypted image URL
   *     <p>javadoc generated by AI
   */
  public void setImageEncrypted(String imageEncrypted) {
    this.imageEncrypted = imageEncrypted;
  }

  /**
   * Gets the UUID of the person.
   *
   * @return UUID
   *     <p>javadoc generated by AI
   */
  public UUID getId() {
    return id;
  }

  /**
   * Sets the UUID of the person.
   *
   * @param id UUID
   *     <p>javadoc generated by AI
   */
  public void setId(UUID id) {
    this.id = id;
  }

  /**
   * Gets the owning episode.
   *
   * @return episode entity
   *     <p>javadoc generated by AI
   */
  public Episode getEpisode() {
    return episode;
  }

  /**
   * Sets the owning episode.
   *
   * @param episode episode entity
   *     <p>javadoc generated by AI
   */
  public void setEpisode(Episode episode) {
    this.episode = episode;
  }

  /**
   * Gets the name of the person.
   *
   * @return person name
   *     <p>javadoc generated by AI
   */
  @Override
  public String getName() {
    return name;
  }

  /**
   * Sets the name of the person.
   *
   * @param name person name
   *     <p>javadoc generated by AI
   */
  @Override
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the role of the person.
   *
   * @return role
   *     <p>javadoc generated by AI
   */
  @Override
  public String getRole() {
    return role;
  }

  /**
   * Sets the role of the person.
   *
   * @param role role
   *     <p>javadoc generated by AI
   */
  @Override
  public void setRole(String role) {
    this.role = role;
  }

  /**
   * Gets the group of the person.
   *
   * @return group
   *     <p>javadoc generated by AI
   */
  @Override
  public String getGroup() {
    return group;
  }

  /**
   * Sets the group of the person.
   *
   * @param group group
   *     <p>javadoc generated by AI
   */
  @Override
  public void setGroup(String group) {
    this.group = group;
  }

  /**
   * Gets the image URL of the person.
   *
   * @return image URL
   *     <p>javadoc generated by AI
   */
  @Override
  public String getImage() {
    return image;
  }

  /**
   * Sets the image URL of the person.
   *
   * @param image image URL
   *     <p>javadoc generated by AI
   */
  @Override
  public void setImage(String image) {
    this.image = image;
  }

  /**
   * Gets the link URL of the person.
   *
   * @return link URL
   *     <p>javadoc generated by AI
   */
  @Override
  public String getLink() {
    return link;
  }

  /**
   * Sets the link URL of the person.
   *
   * @param link link URL
   *     <p>javadoc generated by AI
   */
  @Override
  public void setLink(String link) {
    this.link = link;
  }
}
