package com.github.lamarios.podku.episodes;

public class OfflineProgress {
  private long timeOfProgress;
  private long progress;

  /**
   * Gets the timestamp when progress was recorded.
   *
   * @return epoch milliseconds timestamp
   *     <p>javadoc generated by AI
   */
  public long getTimeOfProgress() {
    return timeOfProgress;
  }

  /**
   * Sets the timestamp when progress was recorded.
   *
   * @param timeOfProgress epoch milliseconds timestamp
   *     <p>javadoc generated by AI
   */
  public void setTimeOfProgress(long timeOfProgress) {
    this.timeOfProgress = timeOfProgress;
  }

  /**
   * Gets the playback progress in seconds.
   *
   * @return playback position in seconds
   *     <p>javadoc generated by AI
   */
  public long getProgress() {
    return progress;
  }

  /**
   * Sets the playback progress in seconds.
   *
   * @param progress playback position in seconds
   *     <p>javadoc generated by AI
   */
  public void setProgress(long progress) {
    this.progress = progress;
  }
}
