/* (C)2026 */
package com.github.lamarios.podku.search;

public class ItunesSearchException extends RuntimeException {
  /**
   * Constructs an ItunesSearchException with a message.
   *
   * @param message error message
   *     <p>javadoc generated by AI
   */
  public ItunesSearchException(String message) {
    super(message);
  }
}
