/* (C)2026 */
package com.github.lamarios.podku.search;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.lamarios.podku.utils.FastUrlCrypto;
import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SearchResult {
  @JsonProperty("collectionId")
  private Long collectionId;

  @JsonProperty("collectionName")
  private String collectionName;

  @JsonProperty("artistName")
  private String artistName;

  @JsonProperty("feedUrl")
  private String feedUrl;

  @JsonProperty("artworkUrl600")
  private String artworkUrl;

  @JsonProperty("genres")
  private List<String> genres;

  @JsonProperty("color")
  private String color;

  /**
   * Returns the encrypted artwork URL.
   *
   * @return encrypted URL string
   * @throws Exception if encryption fails
   *     <p>javadoc generated by AI
   */
  public String getArtworkUrlEncrypted() throws Exception {
    return FastUrlCrypto.instance.encrypt(artworkUrl);
  }

  /**
   * Gets the vibrant color hex code for the artwork.
   *
   * @return hex color string
   *     <p>javadoc generated by AI
   */
  public String getColor() {
    return color;
  }

  /**
   * Sets the vibrant color hex code for the artwork.
   *
   * @param color hex color string
   *     <p>javadoc generated by AI
   */
  public void setColor(String color) {
    this.color = color;
  }

  // getters/setters
  /**
   * Gets the iTunes collection identifier.
   *
   * @return collection ID
   *     <p>javadoc generated by AI
   */
  public Long getCollectionId() {
    return collectionId;
  }

  /**
   * Sets the iTunes collection identifier.
   *
   * @param collectionId collection ID
   *     <p>javadoc generated by AI
   */
  public void setCollectionId(Long collectionId) {
    this.collectionId = collectionId;
  }

  /**
   * Gets the collection name (podcast title).
   *
   * @return collection name
   *     <p>javadoc generated by AI
   */
  public String getCollectionName() {
    return collectionName;
  }

  /**
   * Sets the collection name.
   *
   * @param collectionName collection name
   *     <p>javadoc generated by AI
   */
  public void setCollectionName(String collectionName) {
    this.collectionName = collectionName;
  }

  /**
   * Gets the artist or author name.
   *
   * @return artist name
   *     <p>javadoc generated by AI
   */
  public String getArtistName() {
    return artistName;
  }

  /**
   * Sets the artist or author name.
   *
   * @param artistName artist name
   *     <p>javadoc generated by AI
   */
  public void setArtistName(String artistName) {
    this.artistName = artistName;
  }

  /**
   * Gets the RSS feed URL.
   *
   * @return feed URL
   *     <p>javadoc generated by AI
   */
  public String getFeedUrl() {
    return feedUrl;
  }

  /**
   * Sets the RSS feed URL.
   *
   * @param feedUrl feed URL
   *     <p>javadoc generated by AI
   */
  public void setFeedUrl(String feedUrl) {
    this.feedUrl = feedUrl;
  }

  /**
   * Gets the high-resolution artwork URL.
   *
   * @return artwork URL
   *     <p>javadoc generated by AI
   */
  public String getArtworkUrl() {
    return artworkUrl;
  }

  /**
   * Sets the high-resolution artwork URL.
   *
   * @param artworkUrl artwork URL
   *     <p>javadoc generated by AI
   */
  public void setArtworkUrl(String artworkUrl) {
    this.artworkUrl = artworkUrl;
  }

  /**
   * Gets the list of podcast genres.
   *
   * @return list of genre names
   *     <p>javadoc generated by AI
   */
  public java.util.List<String> getGenres() {
    return genres;
  }

  /**
   * Sets the list of podcast genres.
   *
   * @param genres list of genre names
   *     <p>javadoc generated by AI
   */
  public void setGenres(java.util.List<String> genres) {
    this.genres = genres;
  }
}
