/* (C)2026 */
package com.github.lamarios.podku.search;

import com.github.lamarios.podku.podcasts.Podcast;
import com.github.lamarios.podku.podcasts.PodcastService;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/search")
@Tag(name = "Search")
public class SearchController {
  private final PodcastService podcastService;
  private final ItunesPodcastSearch itunesPodcastSearch;

  /**
   * Constructs the SearchController with required dependencies.
   *
   * @param podcastService service for podcast retrieval
   * @param itunesPodcastSearch search client for iTunes directory
   *     <p>javadoc generated by AI
   */
  @Autowired
  public SearchController(PodcastService podcastService, ItunesPodcastSearch itunesPodcastSearch) {
    this.podcastService = podcastService;
    this.itunesPodcastSearch = itunesPodcastSearch;
  }

  /**
   * Searches the iTunes directory for podcasts, excluding already subscribed feeds.
   *
   * @param query the search term
   * @param limit maximum results to return
   * @return list of matching search results
   *     <p>javadoc generated by AI
   */
  @GetMapping
  public List<SearchResult> search(
      @RequestParam("query") String query, @RequestParam("limit") int limit) {
    var subscribedPodcasts = podcastService.getPodcasts().stream().map(Podcast::getUrl).toList();

    List<SearchResult> results = itunesPodcastSearch.search(query, limit);
    results.removeIf(result -> subscribedPodcasts.contains(result.getFeedUrl()));
    return results;
  }
}
