/* (C)2026 */
package com.github.lamarios.podku.websockets;

import java.util.Arrays;

public class WebSocketMessage<T> {
  public enum Type {
    playerStatus(PlayerStatus.class),
    getPlayerStatus(null),
    remoteCommand(RemoteCommand.class),
    playerInfo(WebsocketClient.class),
    clientList(ClientList.class),
    transferPlayback(TransferPlayback.class),
    pong(PlayerStatus.class),
    playbackProgress(PlaybackProgress.class);
    private final Class<?> clazz;

    Type(Class<?> clazz) {
      this.clazz = clazz;
    }

    /**
     * Resolves the WebSocket message Type enum corresponding to a payload class.
     *
     * @param clazz payload class type
     * @return matching Type enum
     *     <p>javadoc generated by AI
     */
    public static Type getFromClass(Class<?> clazz) {
      return Arrays.stream(Type.values()).filter(t -> t.clazz == clazz).findFirst().orElseThrow();
    }

    /**
     * Returns the payload class for this message type.
     *
     * @return payload class type
     *     <p>javadoc generated by AI
     */
    public Class<?> getClazz() {
      return clazz;
    }
  }

  private Type type;
  private T message;

  /**
   * Default constructor.
   *
   * <p>javadoc generated by AI
   */
  public WebSocketMessage() {}

  /**
   * Constructs a WebSocketMessage with a specified type and payload.
   *
   * @param type message type
   * @param message payload content
   *     <p>javadoc generated by AI
   */
  public WebSocketMessage(Type type, T message) {
    this.type = type;
    this.message = message;
  }

  /**
   * Gets the message type.
   *
   * @return message Type
   *     <p>javadoc generated by AI
   */
  public Type getType() {
    return type;
  }

  /**
   * Sets the message type.
   *
   * @param type message Type
   *     <p>javadoc generated by AI
   */
  public void setType(Type type) {
    this.type = type;
  }

  /**
   * Gets the message payload.
   *
   * @return payload content
   *     <p>javadoc generated by AI
   */
  public T getMessage() {
    return message;
  }

  /**
   * Sets the message payload.
   *
   * @param message payload content
   *     <p>javadoc generated by AI
   */
  public void setMessage(T message) {
    this.message = message;
  }
}
