/* (C)2026 */
package com.github.lamarios.podku.websockets;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.CloseStatus;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;
import org.springframework.web.socket.handler.TextWebSocketHandler;

@Component
public class WebSocketHandler extends TextWebSocketHandler {
  private static final Logger log = LogManager.getLogger();
  private final WebSocketSessionManager webSocketSessionManager;

  /**
   * Constructs WebSocketHandler with session manager dependency.
   *
   * @param webSocketSessionManager manager handling sessions
   *     <p>javadoc generated by AI
   */
  @Autowired
  public WebSocketHandler(WebSocketSessionManager webSocketSessionManager) {
    this.webSocketSessionManager = webSocketSessionManager;
  }

  /**
   * Invoked after a new WebSocket connection has been opened.
   *
   * @param session the established session
   *     <p>javadoc generated by AI
   */
  @Override
  public void afterConnectionEstablished(WebSocketSession session) {
    webSocketSessionManager.register(session);
    log.info("New websocket session");
  }

  /**
   * Handles incoming text messages from clients.
   *
   * @param session the sender's session
   * @param message the received text message
   *     <p>javadoc generated by AI
   */
  @Override
  protected void handleTextMessage(WebSocketSession session, TextMessage message) {
    // If you don’t want client messages, ignore this
    webSocketSessionManager.handleMessage(session, message);
  }

  /**
   * Invoked after a WebSocket connection has been closed by either side.
   *
   * @param session the closed session
   * @param status close status
   *     <p>javadoc generated by AI
   */
  @Override
  public void afterConnectionClosed(WebSocketSession session, CloseStatus status) {
    webSocketSessionManager.remove(session);
    log.info("User disconnected");
  }
}
